name: fastapi CI/CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Install Poetry
        run: pip3 install poetry
      
      - name: Virtual ENV
        user: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles("**/pyproject.toml") }}
          restore-keys:
            - ${{ runner.os }}-venv-
        
      - name: Instal dependencies
        run: poetry install
        if: steps.cache-venv.outputs.cache-hit != 'true'
      
      - name: Run tests
        run: poetry shell && pytest tests/
      
      - name: Create archve of dependencies
        run: 
          cd ./.venv/lib/python3.8/site-packages/
          zip -r9 ../../../../api.zip
      
      - name: Add api files to ZIP file
        run: cd ./api && zip -g ../api.zip -r .
      
      - name: Upload ZIP file to S3
        user: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
