name: fastapi CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Install Poetry
        run: pip3 install poetry && poetry config virtualenvs.in-project true
      
      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-venv-
        
      - name: Instal dependencies
        run: poetry install -v
        if: steps.cache-venv.outputs.cache-hit != 'true'
      
      - name: Run tests
        run: poetry run pytest
      
      - name: Create archive of dependencies
        run: 
          cd ./.venv/lib/python3.8/site-packages &&
          zip -r9 ../../../../api.zip .
      
      - name: Add api files to ZIP file
        run: cd ./api && zip -g ../api.zip -r .
      
      - name: Upload ZIP file to artifact store
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Download ZIP file from S3
        uses: actions/download-artifact@v2
        with:
          name: api
      
      - name: Upload ZIP file to S3
        run: aws s3 cp api.zip s3://${{ secrets.S3_BUCKET }}/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Deploy new lambda function
        run: aws lambda update-function-code --function-name serverless-fastapi --s3-bucket ${{ secrets.S3_BUCKET }} --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
